---

- hosts: all

  handlers:
    - include: handlers/main.yml

  vars:
    username: stemid
    home: /home/stemid

    backup_username: backup
    backup_password: secret.

    build_signal: False
    signal_version: 1.27.3
    signal_tarball_url: "https://github.com/signalapp/Signal-Desktop/archive/v{{ signal_version }}.tar.gz"

    # Packages to install
    packages:
      - tmux
      - nmap
      - tcpdump
      - vim-enhanced
      - autofs
      - libvirt
      - virt-manager
      - gnome-tweaks
      - pidgin
      - evolution
      - firefox-wayland
      - python3-tmuxp
      - nfs-utils
      - cifs-utils
      - redis
      - ansible
      - rpm-build
      - jq
      - nodejs
      - '@Development Tools'
      - smartmontools
      - lshw
      - gnupg2
      - pass
      - irssi
      - '@Multimedia'
      - python3-redis
      - perl-libwww-perl
      - htop

    # Directories to create
    directories:
      - path: "{{ home }}/src"
      - path: /media/nas
        owner: root
        group: root
        mode: "0755"
      - path: "{{ home }}/Utveckling"
      - path: "{{ home }}/.local/bin"
      - path: "{{ home }}/src/rpmbuild"
      - path: "{{ home }}/Bilder/Screenshots"
      - path: "{{ home }}/.vim/colors"
      - path: "{{ home }}/.config/systemd/user"
      - path: "{{ home }}/Ansible/playbooks"
      - path: "{{ home }}/Ansible/roles"
      - path: "{{ home }}/.vim/pack/plugins/start"
      - path: "{{ home }}/.tmuxp"

    # Git repos to clone into ~/src
    repos:
      - src: https://github.com/Anthony25/gnome-terminal-colors-solarized
        dest: "{{ home }}/src/gnome-terminal-colors-solarized"
      - src: https://github.com/tmux-plugins/tmux-resurrect.git
        dest: "{{ home }}/src/tmux-resurrect"
      - src: https://github.com/signalapp/Signal-Desktop.git
        dest: "{{ home }}/src/Signal-Desktop"
      - src: https://github.com/OttoAllmendinger/gnome-shell-screenshot.git
        dest: "{{ home }}/src/gnome-shell-screenshot"
      - src: https://github.com/drahnr/signal-desktop-rpm
        dest: "{{ home }}/src/signal-desktop-rpm"
      - src: https://github.com/lifepillar/vim-solarized8
        dest: "{{ home }}/src/vim-solarized8"
      - src: https://github.com/gcmt/taboo.vim.git
        dest: "{{ home }}/src/taboo.vim"
      - src: https://github.com/vim-scripts/indentpython.vim
        dest: "{{ home }}/src/indentpython.vim"

    # Files to transfer
    files:
      - src: tmux.conf
        dest: "{{ home }}/.tmux.conf"
      - src: vimrc
        dest: "{{ home }}/.vimrc"
      - src: ansible.cfg
        dest: "{{ home }}/.ansible.cfg"
      - src: bashrc
        dest: "{{ home }}/.bashrc"
      - src: rpmmacros
        dest: "{{ home }}/.rpmmacros"
      - src: signal-desktop.spec
        dest: "{{ home }}/src/rpmbuild/SPECS/signal-desktop.spec"
      - src: screenshot.sh
        dest: "{{ home }}/.local/bin/screenshot.sh"
        mode: "0750"
      - src: autossh@.service
        dest: "{{ home }}/.config/systemd/user/autossh@.service"

    # Git repos of vim plugins that will be symlinked under {{ home }}/.vim
    vim_packages:
      - taboo.vim
      - indentpython.vim

    ssh_tunnels: []

  # Override values
  vars_files:
    - "vars/{{ fedora_environment | default('default') }}.yml"

  roles:
    - role: rpmfusion_repo
      distro_version: 30
      tags: become-task

  tasks:
    - name: install packages
      package:
        name: "{{ packages }}"
        state: present
      become: True
      tags: become-task

    - name: create directories
      file:
        path: "{{ item.path }}"
        state: directory
        owner: "{{ item.owner | default(username) }}"
        group: "{{ item.group | default(username) }}"
        mode: "{{ item.mode | default('0750') }}"
      with_items: "{{ directories }}"
      become: True
      tags: become-task

    - name: create rpmbuild directories
      file:
        path: "{{ home }}/src/rpmbuild/{{ item }}"
        state: directory
        mode: "0750"
      with_items:
        - SPECS
        - SOURCES
        - SRPMS
        - tmp
        - BUILDROOT
        - RPMS
        - BUILD

    - name: install files
      template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: "{{ item.mode | default('0600') }}"
      with_items: "{{ files }}"

    - name: clone git repos
      git:
        repo: "{{ item.src }}"
        dest: "{{ item.dest }}"
        accept_hostkey: yes
      with_items: "{{ repos }}"

    - name: ensure redis is started
      service:
        name: redis
        state: started
        enabled: yes
      become: True
      tags: become-task

    - name: run systemctl daemon-reload
      systemd:
        name: autossh@.service
        daemon_reload: yes
        scope: user

    - name: start ssh tunnels
      systemd:
        name: "autossh@{{ item }}.service"
        state: started
        enabled: yes
        scope: user
      with_items: "{{ ssh_tunnels }}"

    - name: install vim-solarized8 colorscheme
      file:
        src: "{{ home }}/src/vim-solarized8/colors/{{ item }}"
        dest: "{{ home }}/.vim/colors/{{ item }}"
        state: link
      with_items:
        - solarized8.vim
        - solarized8_flat.vim
        - solarized8_high.vim
        - solarized8_low.vim

    - name: install vim packages
      file:
        src: "{{ home }}/src/{{ item }}"
        dest: "{{ home }}/.vim/pack/plugins/start/{{ item }}"
        state: link
      with_items: "{{ vim_packages }}"

    - name: reduce swapping to NVME disk
      sysctl:
        name: vm.swappiness
        value: 10
        state: present
        sysctl_file: /etc/sysctl.d/10-swappiness.conf
      become: True
      tags: become-task

    - include: tasks/run-commands.yml
    - include: tasks/setup-autofs.yml
