---

- hosts: all

  handlers:
    - include: handlers/main.yml

  vars:
    username: stemid
    home: /home/stemid

    backup_username: backup
    backup_password: secret.

    build_signal: False
    signal_version: 1.27.3
    signal_tarball_url: "https://github.com/signalapp/Signal-Desktop/archive/v{{ signal_version }}.tar.gz"

    packages:
      - tmux
      - nmap
      - tcpdump
      - vim-enhanced
      - autofs
      - libvirt
      - virt-manager
      - gnome-tweaks
      - pidgin
      - evolution
      - firefox-wayland
      - python3-tmuxp
      - nfs-utils
      - cifs-utils
      - redis
      - ansible
      - rpm-build
      - jq
      - nodejs
      - '@Development Tools'
      - smartmontools
      - lshw
      - gnupg2
      - pass

    directories:
      - path: "{{ home }}/src"
      - path: /media/nas
        owner: root
        group: root
        mode: "0755"
      - path: "{{ home }}/Utveckling"
      - path: "{{ home }}/.local/bin"
      - path: "{{ home }}/src/rpmbuild"
      - path: "{{ home }}/Bilder/Screenshots"
      - path: "{{ home }}/.vim/colors"

    repos:
      - src: https://github.com/Anthony25/gnome-terminal-colors-solarized
        dest: "{{ home }}/src/gnome-terminal-colors-solarized"
      - src: https://github.com/tmux-plugins/tmux-resurrect.git
        dest: "{{ home }}/src/tmux-resurrect"
      - src: https://github.com/signalapp/Signal-Desktop.git
        dest: "{{ home }}/src/Signal-Desktop"
      - src: https://github.com/OttoAllmendinger/gnome-shell-screenshot.git
        dest: "{{ home }}/src/gnome-shell-screenshot"
      - src: https://github.com/drahnr/signal-desktop-rpm
        dest: "{{ home }}/src/signal-desktop-rpm"
      - src: https://github.com/lifepillar/vim-solarized8
        dest: "{{ home }}/src/vim-solarized8"

    files:
      - src: tmux.conf
        dest: "{{ home }}/.tmux.conf"
      - src: vimrc
        dest: "{{ home }}/.vimrc"
      - src: ansible.cfg
        dest: "{{ home }}/.ansible.cfg"
      - src: bashrc
        dest: "{{ home }}/.bashrc"
      - src: rpmmacros
        dest: "{{ home }}/.rpmmacros"
      - src: signal-desktop.spec
        dest: "{{ home }}/src/rpmbuild/SPECS/signal-desktop.spec"
      - src: screenshot.sh
        dest: "{{ home }}/.local/bin/screenshot.sh"
        mode: "0750"

  vars_files:
    - "vars/{{ fedora_environment | default('default') }}.yml"

  tasks:
    - name: install packages
      package:
        name: "{{ item }}"
        state: present
      with_items: "{{ packages }}"
      become: True
      tags: become-task

    - name: create directories
      file:
        path: "{{ item.path }}"
        state: directory
        owner: "{{ item.owner | default(username) }}"
        group: "{{ item.group | default(username) }}"
        mode: "{{ item.mode | default('0750') }}"
      with_items: "{{ directories }}"
      become: True
      tags: become-task

    - name: create rpmbuild directories
      file:
        path: "{{ home }}/src/rpmbuild/{{ item }}"
        state: directory
        mode: "0750"
      with_items:
        - SPECS
        - SOURCES
        - SRPMS
        - tmp
        - BUILDROOT
        - RPMS
        - BUILD

    - name: install files
      template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: "{{ item.mode | default('0600') }}"
      with_items: "{{ files }}"

    - name: clone git repos
      git:
        repo: "{{ item.src }}"
        dest: "{{ item.dest }}"
        accept_hostkey: yes
      with_items: "{{ repos }}"

    - name: ensure redis is started
      service:
        name: redis
        state: started
        enabled: yes
      become: True
      tags: become-task

    - include: tasks/run-commands.yml
    - include: tasks/setup-autofs.yml
